enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "ReVanced/revanced-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/chaosoffire-org/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "apk"
excluded-patches = ""
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = "-e 'Custom branding' -OcustomIcon=icon/YouTube -e 'Change package name' -OpackageName=com.chaosoffire.revanced.youtube"

[Music]
build-mode = "apk"
included-patches = "'Change package name'"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
patcher-args = "-OpackageName=com.chaosoffire.android.apps.youtube.music"

[GooglePhotos]
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Spotify]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts/"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.spotify.music"

# https://github.com/chaosoffire-org/revanced-magisk-module/issues/554
[Music-Extended]
enabled = true
app-name = "Music"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"

[YouTube-Extended]
enabled = true
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon=icon/YouTube-Extended -e 'Custom branding name for YouTube' -OappName='YouTube' -OpackageNameYouTube='com.chaosoffire.revanced.extended.youtube'"

[Twitch]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Twitter]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof' 'Downloads' 'Show seekbar' 'Playback speed'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
